In [10]:
import numpy as np
import numpy
import torch

In [138]:
def btc(bitmap,minmax):
        for i in range(len(minmax)):
            x = int(len(bitmap[i][0])/len(minmax[0][0]))
            y = int(len(bitmap[i][0])/len(minmax[0][0]))
            temp_output = bitmap[i][0].clone()
            block_image = torch.split(torch.cat(torch.split(bitmap[i][0], y, dim=1)), x)
            # min = numpy.split(numpy.concatenate(numpy.split(minmax[i][0],4,axis=1)),4)
            # max = numpy.split(numpy.concatenate(numpy.split(minmax[i][1],4,axis=1)),4)
            min = minmax[i][0].transpose(0,1).flatten()
            max = minmax[i][1].transpose(0,1).flatten()
            
            # print(block_image[0])
            # block_image[0][block_image[0] == 1] = 99
            # print(block_image[0])
            # 
            # print(len(min))
            # print(len(max))
            # print(len(block_image))
            
            for j in range(len(min)):
                block_image[j][block_image[j] == 1] = max[j]
                block_image[j][block_image[j] == 0] = min[j]
            
            # print(len(min))
            # print(len(max))
            # print(min)
            # print(max)
            
            block_image = torch.cat(block_image)
            temp_split = torch.split(block_image,8)
            temp_cat = torch.cat(temp_split,dim=1)
            
            bitmap[i][0]  = temp_cat
            
            # print(min[0])
            # print(block_image)
            # block_image_merge = torch.cat(block_image,out=temp_output)
            # print(block_image_merge)
            # print(block_image_merge.shape)
            # print(temp_output)
            
        return bitmap


temp = np.random.randint(0,2,(1,1,8,8))
minmax = np.random.randint(0,10,(1,2,4,4))
temp = torch.Tensor(temp)
minmax = torch.Tensor(minmax)

In [139]:
print(temp)
print(minmax)
print(temp.shape)
print(minmax.shape)

tensor([[[[0., 0., 0., 1., 1., 1., 0., 0.],
          [1., 1., 1., 1., 0., 1., 0., 0.],
          [0., 0., 1., 1., 0., 0., 0., 1.],
          [0., 1., 1., 1., 1., 1., 1., 0.],
          [1., 1., 1., 0., 0., 0., 1., 1.],
          [1., 0., 0., 1., 1., 0., 0., 0.],
          [1., 0., 1., 1., 1., 0., 0., 0.],
          [0., 1., 0., 0., 0., 0., 1., 0.]]]])
tensor([[[[7., 6., 6., 5.],
          [1., 8., 0., 3.],
          [0., 5., 7., 7.],
          [9., 2., 5., 1.]],

         [[7., 7., 5., 7.],
          [2., 4., 0., 1.],
          [4., 9., 5., 2.],
          [7., 2., 1., 7.]]]])
torch.Size([1, 1, 8, 8])
torch.Size([1, 2, 4, 4])


In [140]:
btm = btc(temp,minmax)

In [141]:
print(btm)

tensor([[[[7., 7., 6., 7., 5., 5., 5., 5.],
          [7., 7., 7., 7., 6., 5., 5., 5.],
          [1., 1., 4., 4., 0., 0., 3., 1.],
          [1., 2., 4., 4., 0., 0., 1., 3.],
          [4., 4., 9., 5., 7., 7., 2., 2.],
          [4., 0., 5., 9., 5., 7., 7., 7.],
          [7., 9., 2., 2., 1., 5., 1., 1.],
          [9., 7., 2., 2., 5., 5., 7., 1.]]]])
